#!/usr/bin/env python3
"""Generate a static large/medium airport glyph database for ADS-B display.

Downloads OurAirports' airports.csv, filters to large_airport and
medium_airport types, and emits a compact C array of {icao, lat, lon, large}
for Map view to draw passive "+ ICAO" glyphs with. Airports the user has
saved as a Location (with runway data from airportdb.io) are drawn with full
runway geometry instead — see draw_saved_airports() in map_view.cpp, which
skips any static-DB entry whose ICAO matches a saved Location.

Usage:
    python3 tools/generate_airports_db.py [--output PATH]
"""

import argparse
import csv
import io
import sys
import urllib.request
from pathlib import Path

AIRPORTS_CSV_URL = "https://davidmegginson.github.io/ourairports-data/airports.csv"
INCLUDED_TYPES = {"large_airport", "medium_airport"}


def download_csv(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": "ADS-B-Display-Airports-DB/1.0"})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read().decode("utf-8")


def parse_airports(csv_text: str):
    airports = []
    reader = csv.DictReader(io.StringIO(csv_text))
    for row in reader:
        if row.get("type") not in INCLUDED_TYPES:
            continue
        icao = (row.get("ident") or "").strip()
        if not icao or len(icao) > 4:
            continue  # skip non-ICAO idents (some entries use local codes)
        try:
            lat = float(row["latitude_deg"])
            lon = float(row["longitude_deg"])
        except (KeyError, ValueError):
            continue
        airports.append({
            "icao": icao,
            "lat": lat,
            "lon": lon,
            "large": 1 if row["type"] == "large_airport" else 0,
        })
    return airports


def write_header(airports, output_path: str):
    with open(output_path, "w") as f:
        f.write("// Auto-generated static airport glyph DB\n")
        f.write(f"// Source: {AIRPORTS_CSV_URL}\n")
        f.write("// Generated by tools/generate_airports_db.py\n")
        f.write(f"// {len(airports)} airports (large_airport + medium_airport)\n")
        f.write("#pragma once\n\n")
        f.write("struct StaticAirport {\n")
        f.write("    char icao[5];\n")
        f.write("    float lat, lon;\n")
        f.write("    unsigned char large; // 1 = large_airport, 0 = medium_airport\n")
        f.write("};\n\n")
        f.write(f"#define AIRPORTS_DB_COUNT {len(airports)}\n\n")
        f.write(f"static const StaticAirport airports_db[AIRPORTS_DB_COUNT] = {{\n")
        for ap in airports:
            f.write(f'    {{"{ap["icao"]}", {ap["lat"]:.6f}f, {ap["lon"]:.6f}f, {ap["large"]}}},\n')
        f.write("};\n")

    size_estimate = len(airports) * 16
    print(f"Wrote {len(airports)} airports to {output_path} (~{size_estimate/1024:.1f} KB)")


def main():
    parser = argparse.ArgumentParser(description="Generate static airport glyph DB for ADS-B display")
    parser.add_argument("--output", type=str, default=None,
                        help="Output path (default: src/ui/airports_db.h)")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    output = args.output or str(repo_root / "src" / "ui" / "airports_db.h")

    print(f"Downloading {AIRPORTS_CSV_URL} ...")
    try:
        csv_text = download_csv(AIRPORTS_CSV_URL)
    except Exception as e:
        print(f"ERROR: failed to download airports.csv: {e}", file=sys.stderr)
        sys.exit(1)

    airports = parse_airports(csv_text)
    if not airports:
        print("ERROR: no airports parsed — check the CSV format/URL", file=sys.stderr)
        sys.exit(1)

    write_header(airports, output)


if __name__ == "__main__":
    main()
